### ISSUE TITLE
Typo on Registration Page

### ISSUE THREAD

**Issue by kanishk16** [ohbm/hackathon2020#176]
# Description
![image](https://user-images.githubusercontent.com/36276423/84476089-47ab1180-acab-11ea-86e6-4528533392ae.png)

# Expected Behavior

Intended to be **World**

# Checklist

- [x] Run `git fetch` to get the most up to date version of `master`
- [x] Searched through existing Issues to confirm this is not a duplicate issue
- [x] Filled out the Description, Expected Behavior, Actual Behavior, and Steps to Reproduce sections above or have edited/removed them in a way that fully describes the issue

**Comment by Remi-Gau** [comment]
Wow. Good catch @kanishk16 .

Will fix this right away. :smile:

**Comment by Remi-Gau** [comment]
Ha just realized this is on the registration page on the OHBM website side of things and on not on the  Brainhack website so I can raise the issue but it can take MUCH longer for it to get fixed given how much work they have.

@cmaumet I think you can confirm that this typo is unlikely to get fixed in a short time, correct?

**Comment by cmaumet** [comment]
Yes unfortunately this is unlikely to get fixed.

**Comment by kanishk16** [comment]
@Remi-Gau Exactly... I realized while going to raise a PR for the same but nonetheless this could be amended for the future events.
