### ISSUE TITLE
Logistics page

### ISSUE THREAD

**Issue by llevitis** [ohbm/hackathon2020#37]
Content that the Logistics page should now display (some of the content might be redundant across this page and the FAQ:

- [x] Hub information - (hub hosts, time-zones)
- [x] Platforms : Crowdcast, Mattermost
- [x] HackTrack: Project submission 
- [x] TrainTrack : general computing requirements, required software
- [ ] Whom to contact on the os sig team and the local hub hosts? (going into FAQ and standalone Contact page)
- [ ] add mattermost and crowdcast images
- [x] slightly increase font size of some paragraphs
- [ ] add hubs image

**Comment by llevitis** [comment]
@cmaumet - please let me know if you have any thoughts on this as well :)

**Comment by cmaumet** [comment]
This looks good to me! Maybe rather than "project template" we could add info about "project submission" (that would include the project template in the end but be a bit more general).

About the Traintrack content will that be in crowdcast? Or do you mean something else?

Maybe info on how to help (if that's not somewhere else) unless we don't want this to be public (maybe by email is better to make that available only to participants):
 - Call for hackathon mentors (with a link to participate)

**Comment by llevitis** [comment]
Thanks @cmaumet ! I started working on the content in this PR which is currently a draft - https://github.com/ohbm/hackathon2020/pull/40
